name: Testing

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say helloppp
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: actions/TestConsoleApp
      with:
        who-to-greet: 'Mona the Octocat'
    - run: echo random-number ${{ steps.foo.outputs.random-number }} 
      shell: bash
